import { NextRequest, NextResponse } from 'next/server'
import { authenticatePOSRequest, addPOSSyncMetadata } from '@/lib/posApiHelper'
import { locationPrisma } from '@/lib/databaseManager'

/**
 * GET /api/pos/sync/[storeCode]/stations/[id]
 * Get a specific station by ID or code
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ storeCode: string; id: string }> }
) {
  try {
    const resolvedParams = await params
    const { storeCode, id } = resolvedParams

    // Authenticate request
    const auth = await authenticatePOSRequest(request, storeCode)
    if (!auth.success) {
      return NextResponse.json(
        { error: auth.error },
        { status: auth.status || 401 }
      )
    }

    // Try to find by ID first, then by stationCode
    let station = null
    const stationId = BigInt(id)
    
    try {
      station = await locationPrisma.station.findFirst({
        where: {
          tblStationId: stationId,
          storeCode
        }
      })
    } catch {
      // If BigInt conversion fails, try by code
    }

    if (!station) {
      station = await locationPrisma.station.findUnique({
        where: { stationCode: id }
      })
    }

    if (!station || station.storeCode !== storeCode) {
      return NextResponse.json(
        { error: 'Station not found' },
        { status: 404 }
      )
    }

    return NextResponse.json({
      success: true,
      data: {
        ...station,
        tblStationId: station.tblStationId.toString()
      }
    })
  } catch (error: any) {
    console.error('Error fetching station:', error)
    return NextResponse.json(
      { error: 'Internal server error', message: error.message },
      { status: 500 }
    )
  }
}

/**
 * PUT /api/pos/sync/[storeCode]/stations/[id]
 * Update a station
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ storeCode: string; id: string }> }
) {
  try {
    const resolvedParams = await params
    const { storeCode, id } = resolvedParams

    // Authenticate request
    const auth = await authenticatePOSRequest(request, storeCode)
    if (!auth.success) {
      return NextResponse.json(
        { error: auth.error },
        { status: auth.status || 401 }
      )
    }

    // Parse request body
    let body
    try {
      body = await request.json()
    } catch (parseError: any) {
      return NextResponse.json(
        { error: 'Invalid JSON in request body' },
        { status: 400 }
      )
    }

    // Find existing station
    let existingStation = null
    const stationId = BigInt(id)
    
    try {
      existingStation = await locationPrisma.station.findFirst({
        where: {
          tblStationId: stationId,
          storeCode
        }
      })
    } catch {
      // Try by code if BigInt fails
    }

    if (!existingStation) {
      existingStation = await locationPrisma.station.findUnique({
        where: { stationCode: id }
      })
    }

    if (!existingStation || existingStation.storeCode !== storeCode) {
      return NextResponse.json(
        { error: 'Station not found' },
        { status: 404 }
      )
    }

    // Prepare update data with POS sync metadata
    const updateData: any = addPOSSyncMetadata({
      updatedBy: body.updatedBy ? BigInt(body.updatedBy) : null
    }, storeCode)

    // Preserve existing syncId - it should not change on update
    // Override the syncId that might have been generated by addPOSSyncMetadata
    updateData.syncId = existingStation.syncId

    // Update allowed fields
    if (body.stationname !== undefined) updateData.stationname = body.stationname
    if (body.isActive !== undefined) updateData.isActive = body.isActive ? 1 : 0
    if (body.stationGroups !== undefined) updateData.stationGroups = body.stationGroups
    if (body.isKitchen !== undefined) updateData.isKitchen = body.isKitchen
    if (body.isBar !== undefined) updateData.isBar = body.isBar
    if (body.isBill !== undefined) updateData.isBill = body.isBill
    if (body.isReport !== undefined) updateData.isReport = body.isReport
    if (body.ipAddress !== undefined) updateData.ipAddress = body.ipAddress

    // Update station
    const updatedStation = await locationPrisma.station.update({
      where: { tblStationId: existingStation.tblStationId },
      data: updateData
    })

    return NextResponse.json({
      success: true,
      message: 'Station updated successfully',
      data: {
        ...updatedStation,
        tblStationId: updatedStation.tblStationId.toString()
      }
    })
  } catch (error: any) {
    console.error('Error updating station:', error)
    return NextResponse.json(
      { error: 'Internal server error', message: error.message },
      { status: 500 }
    )
  }
}

/**
 * DELETE /api/pos/sync/[storeCode]/stations/[id]
 * Delete a station
 */
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ storeCode: string; id: string }> }
) {
  try {
    const resolvedParams = await params
    const { storeCode, id } = resolvedParams

    // Authenticate request
    const auth = await authenticatePOSRequest(request, storeCode)
    if (!auth.success) {
      return NextResponse.json(
        { error: auth.error },
        { status: auth.status || 401 }
      )
    }

    // Find existing station
    let existingStation = null
    const stationId = BigInt(id)
    
    try {
      existingStation = await locationPrisma.station.findFirst({
        where: {
          tblStationId: stationId,
          storeCode
        }
      })
    } catch {
      // Try by code if BigInt fails
    }

    if (!existingStation) {
      existingStation = await locationPrisma.station.findUnique({
        where: { stationCode: id }
      })
    }

    if (!existingStation || existingStation.storeCode !== storeCode) {
      return NextResponse.json(
        { error: 'Station not found' },
        { status: 404 }
      )
    }

    // Delete station
    await locationPrisma.station.delete({
      where: { tblStationId: existingStation.tblStationId }
    })

    return NextResponse.json({
      success: true,
      message: 'Station deleted successfully',
      data: {
        stationCode: existingStation.stationCode,
        tblStationId: existingStation.tblStationId.toString()
      }
    })
  } catch (error: any) {
    console.error('Error deleting station:', error)
    return NextResponse.json(
      { error: 'Internal server error', message: error.message },
      { status: 500 }
    )
  }
}

