-- Extended printer columns for master printer table
ALTER TABLE tbl_master_printer
  ADD COLUMN IF NOT EXISTS is_delete BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS station_code VARCHAR(100),
  ADD COLUMN IF NOT EXISTS is_serial BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS comport VARCHAR(10),
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(200),
  ADD COLUMN IF NOT EXISTS character_per_line INTEGER NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS printer_brand VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS print_method VARCHAR(50) NOT NULL DEFAULT '1',
  ADD COLUMN IF NOT EXISTS col_pre_char INTEGER NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS ip_adress VARCHAR(100);
